apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: loicpincon/app-spa-intex:1.0.1
          ports:
            - containerPort: 80
          env:
            - name: MQTT_URL
              value: mqtt://mosquito
            - name: MONGO_URL
              value: mongodb://database:27017
            - name: PRODUCTION
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: application-service
spec:
  selector:
    app: application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Change to LoadBalancer or NodePort if external access is needed

