apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquito-deployment
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: mosquito
  template:
    metadata:
      labels:
        app: mosquito
    spec:
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
            defaultMode: 420
      containers:
        - name: mosquito
          image: eclipse-mosquitto:2.0.18
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
          env:
            - name: MQTT_URL
              value: mqtt://mosquito
            - name: MONGO_URL
              value: mongodb://database:27017
            - name: PRODUCTION
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: mosquito-service
spec:
  selector:
    app: mosquito
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
  type: ClusterIP
---
---
apiVersion: v1
kind: Service
metadata:
  name: mosquito-service-np
spec:
  selector:
    app: mosquito
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 18883
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mosquito-service-ui
spec:
  selector:
    app: mosquito
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003
  type: ClusterIP
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |-
    per_listener_settings false
    listener 1883
    allow_anonymous true
binaryData: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-passwd
data:
  mqtt_passwd: >-
    user:$7$101$qBkSg+OcnNGPFJVx$rfg67W3hAv8Pj5DouVsua3wItSOgCp7Sey/MYRfTJS2UMHbZdvGLDzReySfciKTvxrcfocl4RyXh7Ayn8Uel+w==
binaryData: {}