services:
  frontend:
    image: loicpincon/app-spa-intex-front:1
    ports:
      - "80:3000"
    networks:
      spa-intex-app-network:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      spa-intex-app-network:
networks:
  spa-intex-app-network: