services:
  frontend:
    build:
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    networks:
      spa-intex-app-network:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      spa-intex-app-network:
networks:
  spa-intex-app-network: