services:
  spa-app:
    image: loicpincon/app-spa-intex:latest
    ports:
      - "80:80"
    networks:
      spa-intex-app-network:
  database:
    image: mongo:latest
    networks:
      spa-intex-app-network:
  mosquito:
    container_name: mosquito
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      spa-intex-app-network:
networks:
  spa-intex-app-network: