name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd front-app && docker build . --file Dockerfile --tag loicpincon/app-spa-intex-front:$(date +%s) @@ docker tag  loicpincon/app-spa-intex-front:$(date +%s) loicpincon/app-spa-intex-front:latest && docker push loicpincon/app-spa-intex-front:$(date +%s)
